import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const atypDisplay = localFont({
  src: [
    { path: "./fonts/AtypDisplayTRIAL-Light.otf", weight: "300" },
    { path: "./fonts/AtypDisplayTRIAL-Regular.otf", weight: "400" },
    { path: "./fonts/AtypDisplayTRIAL-Medium.otf", weight: "500" },
    { path: "./fonts/AtypDisplayTRIAL-Semibold.otf", weight: "600" },
    { path: "./fonts/AtypDisplayTRIAL-Bold.otf", weight: "700" },
  ],
  variable: "--font-aeonik",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`${atypDisplay.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
